### ISSUE TITLE
開発中ページを作る

### ISSUE THREAD

**Issue by ishikawa-naota** [ZDK-UTsukuba/bridge-2024#1]
- [x] dev ブランチを切る
- [x] Astro インストール

**Comment by oageo** [comment]
開発中ページについて進行しているとの噂を聞いていますが、どんな感じですか…？
出来ているならよしなに公開しちゃっても大丈夫です

**Comment by naohanpen** [comment]
@oageo 本体も開発がほぼ終わっていて、正規データを突っ込めば出来上がると思います！

**Comment by oageo** [comment]
次回のミーティング来れるならその場でやっちゃいたいかもです

**Comment by naohanpen** [comment]
@oageo 参加難しいです...！申し訳ありません。
別で調整いただくか、いい感じにやっていただいても大丈夫です💦
