### ISSUE TITLE
Aboutページを書く

### ISSUE THREAD

**Issue by oageo** [ZDK-UTsukuba/bridge-2024#22]
誰が運営しているのか分からないと不安なため

**Comment by Lailai0477** [comment]
- 全代会, 教環について: 教環作の紙面版からとってくる
- IPCについて: 書く

**Comment by oageo** [comment]
Aboutページを書き、その内部に運営者情報を書くことになったため

**Comment by Crow314** [comment]
ref: https://zdk.esa.io/posts/1358#BRIDGE%E3%81%AE%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AE%E9%83%A8%E5%88%86%E3%82%92%E6%9B%B8%E3%81%8F

**Comment by Lailai0477** [comment]
IPCについて

情報処理推進特別委員会（Information-technology Promotion Committee, IPC）は全代会の委員会の一つで、本学における学生による情報処理に関する活動の推進を主な目的として設立された特別委員会です。主な活動として、[全代会Webサイト](https://www.stb.tsukuba.ac.jp/~zdk/)の開発・管理、[Webページ学生委員会](https://www.stb.tsukuba.ac.jp/~webgaku/)への人員派遣、[新歓Web](https://shinkan-web.zdk.tsukuba.ac.jp/)の管理・運営、筑波大学に関連する情報系技術者コミュニティ「[UNTIL.](https://until-tsukuba.github.io/)」の運営などを行っています。

（全代会Webサイト、Web学、新歓Web、UNTIL.のページにリンクを張れるとよい）

**Comment by Lailai0477** [comment]
from 教環
fixed by @Crow314 

>全代会（全学学類･専門学群･総合学域群代表者会議）は、大学の公式な学生代表組織です。
>学生全体の意見をまとめて大学に届け、学生生活や学習環境の改善を目的として活動しています。
>
>全代会は学生からの意見や要望を集め、それを大学の運営や教育方針に反映させるための議論や提案を行います。
>全代会は学類等の教育組織から選出される代表者や有志の学生で構成されており、定期的な会議やイベントを通じて、学生と大学の橋渡し役としての役割を果たします。
>また、大学内での問題提起や改善に取り組むだけでなく、他大学との交流や情報共有も行うことがあり、学生の意見を幅広く発信する場ともなっています。

>全代会教育環境委員会は、全代会の委員会、ワーキンググループの一つで、学生の学習環境を向上させるための活動を行っています。
>主に、授業の質や教室の設備、学習サポートの充実について、大学に問題提起や改善提案を行っています。
>基本的には、学生から集めた授業に関する意見や要望をアンケートを通じて収集し、定期的に大学側と協議して改善を図ります。
>また、授業評価のアンケート結果をもとに教員との意見交換会や懇談会を開催し、教育方針や学習支援に関する具体的な改善策の検討も行っています。

**Comment by oageo** [comment]
> [全代会（全学学類・専門学群・総合学域群代表者会議）](https://www.zdk.tsukuba.ac.jp)は、筑波大学の公的な学生代表組織です。
> 学生の皆様の意見をまとめ、大学に届けることにより、学習環境や生活の改善を主な目的として活動しています。
>
> 全代会は、各学類等の教育組織から選出される学類等代表や、有志の学生で構成されており、定期的な会議やイベント等を通して、学生と大学との橋渡し役としての役割を果たしています。また、大学内での問題提起や改善に取り組むだけでなく、他大学の学生組織との交流や情報共有も行っております。
>
> 詳細は[全代会Webサイト](https://www.stb.tsukuba.ac.jp/~zdk/about)をご覧ください。

**Comment by Lailai0477** [comment]
以下昔のWebサイトの文言を少し変えたもの
（紙面でも発行しております）は発行してない時点で公開するならなくても良いかも


BRIDGEについて
「BRIDGE」は、筑波大学 全学学類・専門学群・総合学域群代表者会議（以下、全代会）教育環境委員会および情報処理推進特別委員会が運営する授業評価サイトです\。学類と学類の架け橋になるように、という意味で名付けられました。

　筑波大学は総合大学で25もの学類・専門学群があり、本学ではそれらの様々な分野の授業を自由に履修することができます。しかし、これまで接点のなかった授業となると難易度や雰囲気など情報を得ることが難しく、履修をためらってしてしまう方も多いのではないでしょうか。そういった方々のために我々、教育環境委員会はこのBRIDGEを作成しています。Webサイトは情報処理推進特別委員会が運営しております。
　このサイトに掲載されている授業の情報はすべて各学類等の学生達の目線で書かれたものです。そのためシラバスには書かれていないような情報が含まれています。このような新鮮な情報を見て、興味のある授業を気軽に履修してみましょう！


BRIDGEの注意点
　BRIDGEに掲載している情報は、今年度の科目情報とは異なる場合があります。また、誤った情報が記載されている可能性もありますので、開設授業科目一覧も確認していただければと思います。もし記載されている情報に誤りを発見された場合、お手数ですが <連絡先> にご連絡いただけると幸いです。

**Comment by oageo** [comment]
> 全代会教育環境委員会は、全代会内部の「委員会（ワーキンググループ）」の1つで、学生の学習環境を向上させるための活動を行っています。主に講義の質や教室の設備、学習のサポートについて、大学に対し問題提起や改善を求めています。
> 
> 基本的には、学生から集めた授業に関する意見や要望をアンケートを通じて収集し、定期的に大学側と協議して改善を図ります。また、アンケート結果をもとに教員との意見交換会や懇談会を開催し、教育方針や学習支援に関する具体的な改善策の検討も行っています。

**Comment by Lailai0477** [comment]
運営者情報とBRIDGEについてをBRDGEに流し込んだ
BRIDGEの使い方を書く必要がある

**Comment by oageo** [comment]
委員長連絡会で教育環境委員会に使い方を書いてほしい旨を伝えた

**Comment by Crow314** [comment]
#29 でClose？ かと思ったけど、使い方を書く必要があるのか

**Comment by Crow314** [comment]
Issue分割しますか？

**Comment by oageo** [comment]
本番データ流し込み後に書いたほうが良いという方針に

無くても最悪公開が可能なため、使い方を書くという別Issueを立てた後にクローズするという話で

**Comment by Lailai0477** [comment]
使い方を #39 に分割したためclose
