### ISSUE TITLE
いい感じな CSS フレームワーク欲しい

### ISSUE THREAD

**Issue by ishikawa-naota** [ZDK-UTsukuba/bridge-2024#3]
フロント担当大臣 @shiomanju さま～

### 検討されている案
- [Bulma](https://bulma.io/documentation/ "Bulma のドキュメントページ")
- Bootstrap
- ピュア

**Comment by ishikawa-naota** [comment]
- https://mantine.dev/
- [Pure.css](https://purecss.io/)
- ZDK Original Framework

**Comment by shiomanju** [comment]
正直どれも使ったことないからどれでもいいけど、ざっと調べた感じだとBulmaが気になる。

**Comment by Zect3279** [comment]
じゃぁ、Bulmaで行こう

**Comment by ishikawa-naota** [comment]
しゃあそれで
