### ISSUE TITLE
UI を決めよう

### ISSUE THREAD

**Issue by ishikawa-naota** [ZDK-UTsukuba/bridge-2024#5]
- 画面
- 繊維
- 機能

**Comment by shiomanju** [comment]
![20240625_210551.jpg](https://github.com/ZDK-UTsukuba/bridge-2024/assets/83050142/79818c79-979e-4a63-bf1d-67103ba74370)

- メールアドレスはリンクにしたい

**Comment by shiomanju** [comment]
- 検索項目 何で検索できるようにするか
    - 科目名、番号、評価内容 etc.
- どうやって検索する？
    - JSONをJSで単純に全探索
    - データベース
- 聞いてない教科の扱い
    - kdbには載ってるけどアンケートの回答にはない科目も扱うなら、検索件数数万件になる。フロントエンドで回すのは厳しい？
    - アンケート結果ベースで検索するならJSONで十分？
